# Generated by Django 3.2 on 2022-08-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_adt',
            new_name='created_at',
        ),
    ]
